<?php

namespace AppBundle\Repository;

/**
 * MerciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerciRepository extends \Doctrine\ORM\EntityRepository
{
}
